### PR TITLE
Yeoman generator

### PR DESCRIPTION
**Pull request by iiegor**
This PR arises from the need to create a generator to simplify things when creating an application with this boilerplate. 

This was discussed in #44.

### CODE REVIEW

**Comment by iiegor** [comment]
If this PR is accepted, remember to publish the npm module :grimacing:

**Comment by choonkending** [comment]
@iiegor you're a saint. I haven't reviewed it yet, but just seeing the PR title makes me happy haha

**Comment by iiegor** [comment]
@choonkending :laughing:. Thinking about this, maybe we can make more simple the generator templates and create a subgenerator for creating new components, reducers... etc (something like ``yo react-webpack-node:component MyComponent``).

What do you think?

**Comment by choonkending** [comment]
@iiegor Had a look at the PR, it looks great. I agree that we could make simpler generator templates! Go for it!

**Comment by aaronmng** [comment]
@iiegor you are a legend for working on this PR. Yes, I was thinking of some sub generator for all the different components.

@choonkending only started looking at this project and it's a great base for new software. Keep up the good work.

**Comment by choonkending** [comment]
@aaronmng Thanks :)

**Comment by iiegor** [comment]
I think all basic functions are done! If there is some feature missing or that you want to add, tell me :smile: 

- - - - 
**Usage:**
``yo react-webpack-node`` *Generate the project structure*
``yo react-webpack-node:component myComponent`` *Create a component (with stylesheet)*
``yo react-webpack-node:reducer myReducer`` *Create a reducer*
``yo react-webpack-node:container myContainer`` *Create a container*
``yo react-webpack-node:constant index MY_CONST`` *Create a constant (where index is the constants file name)*

**Comment by choonkending** [comment]
@iiegor Yay!!!!

**Comment by choonkending** [comment]
Closing as there is an awesome repository [here](https://github.com/iiegor/generator-react-webpack-node) by @iiegor . Thanks!! :hand:

**Pull request closed without merging**
