### PR TITLE
Feature/auth flow

### PR DESCRIPTION
**Pull request by choonkending**
- Upgrade to react-router 2.0, redux-simple-router 2.0
https://github.com/choonkending/react-webpack-node/issues/114
- Auth flow
https://github.com/choonkending/react-webpack-node/issues/107

### CODE REVIEW

**Comment by hoodsy** [comment]
@choonkending the only reason I could see for the ```req.isAuthenticated()``` always returning false is the session cookie not correctly being stored.. but I'm not sure why this would be the case.

**Comment by choonkending** [comment]
@hoodsy I know! I initially thought I was not sending cookies because of isomorphic-fetch, but I have all the proper arguments specified in the fetch request. I'll have a look again later with a clearer mind.

**Comment by choonkending** [comment]
I can verify that cookies are not sent from server fetch. Possibly because you shouldn't need to be checking whether you are authenticated via API if you're on the same-origin. 

Anyway, I think I have a solution from this brilliant repo. https://github.com/erikras/react-redux-universal-hot-example/blob/c22755e52565f0bfc829d88d31cb92b9749b8145/src/routes.js#L16

Testing it now before pushing it for you to have a go at it.

**Comment by choonkending** [comment]
@hoodsy Have a go at it. I'll be merging it in soon-ish :)

Still need to solve the issue of redirecting *after* logging in, but I think that can be another branch.

**Comment by choonkending** [comment]
@psimyn The long awaited fix.

**Comment by hoodsy** [comment]
@choonkending looks great man! excited to get this into my project as well :+1:

**Pull request merged**
