### PR TITLE
Css modules

### PR DESCRIPTION
**Pull request by psimyn**
switch css-loader to module mode, replace all className strings and import styles per-component

Things that could be better:
- classes with hyphens in names have the somewhat ugly ```{styles['class--name']}```
- Possibly a better way to have multiple classes than the ugly string joins

### CODE REVIEW

**Comment by choonkending** [comment]
Need to resolve merge conflict

**Comment by psimyn** [comment]
one remaining issue preventing dev server from working (window not defined) - possibly due to not using ExtractTextPlugin but unsure

feel free to attempt :)

**Comment by choonkending** [comment]
I removed extracttextplugin from dev server because it didn't hotload the CSS :p

Interesting. Will try to get this out and ship tonight.

**Comment by choonkending** [comment]
Haven't pulled this and tested but was reviewing the code. I think server side should not be extracting the CSS which was why we left it out of commonloaders

**Comment by choonkending** [comment]
@psimyn Good work!

I've also found a fix for the problem https://github.com/webpack/css-loader/issues/59#issuecomment-109793167


That's the new config. tl;dr `css/locals` for server-side prerendering. Also I have to remove the css `<link>` on dev environment. Otherwise the stylesheet would override your hot loader in certain cases.

```javascript
var path = require("path");
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var webpack = require("webpack");

var assetsPath = path.join(__dirname, "..", "public", "assets");
var publicPath = "assets/";

var WEBPACK_HOST = "localhost";
var WEBPACK_PORT = 3001;

var commonLoaders = [
  {
    /*
     * TC39 categorises proposals for babel in 4 stages
     * Read more http://babeljs.io/docs/usage/experimental/
     */
    test: /\.jsx$/,
    loaders: ["react-hot", "babel-loader?stage=0"],
    include: path.join(__dirname, "..", "app")
  },
  {
    test: /\.js$/,
    loaders: ["react-hot", "babel-loader?stage=0"],
    include: path.join(__dirname, "..", "app")
  },
  { test: /\.png$/, loader: "url-loader" },
  { test: /\.jpg$/, loader: "file-loader" },
  { test: /\.html$/, loader: "html-loader" }
];

module.exports = [
  {
    // The configuration for the client
    name: "browser",
    /* The entry point of the bundle
     * Entry points for multi page app could be more complex
     * A good example of entry points would be:
     * entry: {
     *   pageA: "./pageA",
     *   pageB: "./pageB",
     *   pageC: "./pageC",
     *   adminPageA: "./adminPageA",
     *   adminPageB: "./adminPageB",
     *   adminPageC: "./adminPageC"
     * }
     *
     * We can then proceed to optimize what are the common chunks
     * plugins: [
     *  new CommonsChunkPlugin("admin-commons.js", ["adminPageA", "adminPageB"]),
     *  new CommonsChunkPlugin("common.js", ["pageA", "pageB", "admin-commons.js"], 2),
     *  new CommonsChunkPlugin("c-commons.js", ["pageC", "adminPageC"]);
     * ]
     */
    context: path.join(__dirname, "..", "app"),
    entry: {
      app:[ 'webpack-dev-server/client?http://' + WEBPACK_HOST + ":" + WEBPACK_PORT,
       'webpack/hot/only-dev-server',
        "./app" ]
    },
    output: {
      // The output directory as absolute path
      path: assetsPath,
      // The filename of the entry chunk as relative path inside the output.path directory
      filename: "[name].js",
      // The output path from the view of the Javascript
      publicPath: publicPath

    },
    module: {
      preLoaders: [{
        test: /\.js$|.jsx$/,
        exclude: /node_modules/,
        loaders: ["eslint"]
      }],
      loaders: commonLoaders.concat([
          { test: /\.scss$/,
            loader: 'style!css?module&localIdentName=[local]__[hash:base64:5]' +
              '&sourceMap!sass?sourceMap&outputStyle=expanded' +
              '&includePaths[]=' + (path.resolve(__dirname, './node_modules'))
          }
      ])
    },
    resolve: {
      extensions: ['', '.react.js', '.js', '.jsx', '.scss'],
      modulesDirectories: [
        "app", "node_modules"
      ]
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin()
    ]
  }, {
    // The configuration for the server-side rendering
    name: "server-side rendering",
    context: path.join(__dirname, "..", "app"),
    entry: {
      app: "./app",
      header: "./elements/Header.react"
    },
    target: "node",
    output: {
      // The output directory as absolute path
      path: assetsPath,
      // The filename of the entry chunk as relative path inside the output.path directory
      filename: "[name].server.js",
      // The output path from the view of the Javascript
      publicPath: publicPath,
      libraryTarget: "commonjs2"
    },
    externals: /^[a-z\-0-9]+$/,
    module: {
      loaders: commonLoaders.concat([
          { test: /\.scss$/,
            loader: 'css/locals?module&localIdentName=[local]__[hash:base64:5]' +
              '&sourceMap!sass?sourceMap&outputStyle=expanded' +
              '&includePaths[]=' + (path.resolve(__dirname, './node_modules'))
          }
      ])
    },
    resolve: {
      extensions: ['', '.react.js', '.js', '.jsx', '.scss'],
      modulesDirectories: [
        "app", "node_modules"
      ]
    }
  }
];

```

Woohoo!

**Comment by psimyn** [comment]
Good find, I'll make that change and fix the node modules path as well

**Comment by choonkending** [comment]
@psimyn I think this wouldn't work for the browser-side. The scss loader for browser is not equal to how it's being handled on the server side. Tested this a minute ago and there were no styles :(. 

What worked for me was:

1. Removing `scss` test loader in commonLoaders
2. Adding this to browser-side bundle (we still need style-loader)
```javascript
      loaders: commonLoaders.concat([
          { 
            test: /\.scss$/,
            loader: 'style!css?module&localIdentName=[local]__[hash:base64:5]' +
              '&sourceMap!sass?sourceMap&outputStyle=expanded' +
              '&includePaths[]=' + (path.resolve(__dirname, './node_modules'))
          }
      ])
```
3. Adding this to the server-side bundle
```javascript
       loaders: commonLoaders.concat([
          { 
            test: /\.scss$/,
            loader: 'css/locals?module&localIdentName=[local]__[hash:base64:5]' +
              '&sourceMap!sass?sourceMap&outputStyle=expanded' +
              '&includePaths[]=' + (path.resolve(__dirname, './node_modules'))
          }
      ])
```

After that we can :shipit: with some :shaved_ice:

**Comment by choonkending** [comment]
Also, this PR deserves a version bump. It's a good change

**Comment by psimyn** [comment]
I think 3f7339f does what you mean.

If not please make a patch - all these configs are getting confusing to manage :(

**Comment by choonkending** [comment]
Making a patch now :D I think I got a fix for both webpack config and the
hot loader config.

Btw, didn't know you could make a patch lol.

On Sat, Jul 25, 2015 at 1:11 PM, Simon Knox <notifications@github.com>
wrote:

> I think 3f7339f
> <https://github.com/choonkending/react-webpack-node/commit/3f7339fd61a00db85aea36f31b4bf02a253f90d6>
> does what you mean.
>
> If not please make a patch - all these configs are getting confusing to
> manage :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choonkending/react-webpack-node/pull/35#issuecomment-124792426>
> .
>



-- 
Kind regards,
Choon Ken Ding

**Comment by choonkending** [comment]
I'll merge it in and push a fix to it.

**Comment by choonkending** [comment]
For reference, this is the last commit https://github.com/choonkending/react-webpack-node/commit/9e3a4fef5dd918be359b288a5ff68d490e0f1def.


@psimyn Awesome work man. Css modules are in!!!!

**Pull request merged**
