### PR TITLE
CSSNext + StyleLint

### PR DESCRIPTION
**Pull request by jrodl3r**
Re: #296

### CODE REVIEW

**Comment by choonkending** [comment]
Really nice work! I see `cssnext` as the way moving forward.

I'll try my best to review and get this merged once the conflicts have been resolved (sorry).

**Comment by jrodl3r** [comment]
1 step at a time 😉

**Comment by choonkending** [comment]
@jrodl3r Do you mind resolving the conflicts when you get a chance? I think this is a good change!

**Comment by jrodl3r** [comment]
@choonkending 👍

**Comment by jrodl3r** [comment]
**todo:**

- [ ] Update docs

**Comment by choonkending** [comment]
@jrodl3r Thanks for the hard work put into this buddy!

**Pull request merged**
